version: "3.8"
services:
  back:
    build:
      context: chaeda_spring
      dockerfile: Dockerfile
    restart: always
    network_mode: "host"
    environment:
      - TZ=Asia/Seoul
    env_file:
      - .env