spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    #    url: jdbc:postgresql://114.70.23.79:5432/spring?user=chaeda&password=chaeda
    url: jdbc:postgresql://localhost:5432/spring?user=chaeda&password=chaeda
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  profiles:
    include: aws, swagger, auth
  sql:
    init:
      mode: always

jwt:
  expiration_time: 86400000 #1일
  secret:
    key: dbc8f198571ff39133958631658a18849423c9e013eaa308210267feec4799fcf85d099d7d8b984ecb2ebe6a6a85f82464ecd0272c55c78f89b4960ea51edc32


#server:
#  servlet:
#    encoding:
#      force-response: true
